<h1>Klasifikasi SMS Spam</h1>
Klasifikasi Menggunakan Simple Recurrent Neural Network mendapatkan akurasi sebesar 93%

Author : LyanDoo

Sumber Dataset:
<i>https://gist.github.com/agtbaskara/a1a7017027cc1df9d35cf06e1e5575b7</i>


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('dataset_sms_spam_v1.csv')
df.head()

Teks  label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...      2
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...      2
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...      2
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...      2
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...      2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Teks    1143 non-null   object
 1   label   1143 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 18.0+ KB


In [ ]:
df['Teks'] = df['Teks'].str.lower()
df.head()

Teks  label
0  [promo] beli paket flash mulai 1gb di my telko...      2
1  2.5 gb/30 hari hanya rp 35 ribu spesial buat a...      2
2  2016-07-08 11:47:11.plg yth, sisa kuota flash ...      2
3  2016-08-07 11:29:47.plg yth, sisa kuota flash ...      2
4  4.5gb/30 hari hanya rp 55 ribu spesial buat an...      2

In [ ]:
df['Teks'] = df['Teks'].str.replace('[^a-zA-Z ]','')
df['Teks']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


0       promo beli paket flash mulai gb di my telkomse...
1        gb hari hanya rp  ribu spesial buat anda yang...
2        plg yth sisa kuota flash anda kb download myt...
3        plg yth sisa kuota flash anda kb download myt...
4       gb hari hanya rp  ribu spesial buat anda yang ...
                              ...                        
1138         yooo sama oke nanti aku umumin di grup kelas
1139     sebelumnya ga ad nulis kerudung kirain warna ...
1140                                    mba mau kirim  ya
1141       nama  beaok bwrangkat pagimau cas atay tranfer
1142                           no bri atas nama kamu mana
Name: Teks, Length: 1143, dtype: object

In [ ]:
df['Teks'] = df['Teks'].str.strip()
df['Teks']

0       promo beli paket flash mulai gb di my telkomse...
1       gb hari hanya rp  ribu spesial buat anda yang ...
2       plg yth sisa kuota flash anda kb download myte...
3       plg yth sisa kuota flash anda kb download myte...
4       gb hari hanya rp  ribu spesial buat anda yang ...
                              ...                        
1138         yooo sama oke nanti aku umumin di grup kelas
1139    sebelumnya ga ad nulis kerudung kirain warna jins
1140                                    mba mau kirim  ya
1141       nama  beaok bwrangkat pagimau cas atay tranfer
1142                           no bri atas nama kamu mana
Name: Teks, Length: 1143, dtype: object

In [ ]:
df.head()

Teks  label
0  promo beli paket flash mulai gb di my telkomse...      2
1  gb hari hanya rp  ribu spesial buat anda yang ...      2
2  plg yth sisa kuota flash anda kb download myte...      2
3  plg yth sisa kuota flash anda kb download myte...      2
4  gb hari hanya rp  ribu spesial buat anda yang ...      2

In [ ]:
df['Teks'][4]

'gb hari hanya rp  ribu spesial buat anda yang terpilih aktifkan sekarang juga di  buruan skb'

In [ ]:
teks_corpus = list(df['Teks'])
teks_corpus

['promo beli paket flash mulai gb di my telkomsel app dpt extra kuota gb g lte dan extra nelpon hingga mnthr buruan cek  di tselmemytsel sk',
 'gb hari hanya rp  ribu spesial buat anda yang terpilih aktifkan sekarang juga di  promo sd  nov buruan aktifkan sekarang sk',
 'plg yth sisa kuota flash anda kb download mytelkomsel apps di httptselmetsel utk cek kuotabeli paket flash atau hub',
 'plg yth sisa kuota flash anda kb download mytelkomsel apps di httptselmetsel utk cek kuotabeli paket flash atau hub',
 'gb hari hanya rp  ribu spesial buat anda yang terpilih aktifkan sekarang juga di  buruan skb',
 'hari lagi  ekstra pulsa rb dg beli paket internet bulanan di mytelkomsel utk pembelian pertama sjk augsept cek detail promo di tselmemytsel',
 'ada iring dgn tarif rp hr perpanjangan rp hr dari hits armada  pencuri hati tekan  lalu okcall info',
 'akhir bulan harus tetap eksis loh internetan pake volume ultima mbhr hrga mulai rp rb di  tariflokasi cek di tselmefl',
 'aktifkan iring coboy 

In [ ]:
len(teks_corpus)

1143

In [ ]:
teks_label = df['label'].values
teks_label

array([2, 2, 2, ..., 0, 0, 0])

In [ ]:
teks_label.shape

(1143,)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer(num_words=500,oov_token='-')
tokenizer.fit_on_texts(teks_corpus)
tokenizer.word_index

{'-': 1,
 'di': 2,
 'anda': 3,
 'ke': 4,
 'ini': 5,
 'info': 6,
 'ada': 7,
 'yg': 8,
 'aku': 9,
 'mau': 10,
 'dan': 11,
 'hadiah': 12,
 'dari': 13,
 'sms': 14,
 'no': 15,
 'pin': 16,
 'cek': 17,
 'rp': 18,
 'nama': 19,
 'aja': 20,
 'klik': 21,
 'pulsa': 22,
 'paket': 23,
 'hub': 24,
 'saya': 25,
 'yang': 26,
 'ya': 27,
 'untuk': 28,
 'hari': 29,
 'promo': 30,
 'jt': 31,
 'resmi': 32,
 'atau': 33,
 'rb': 34,
 'gb': 35,
 'selamat': 36,
 'isi': 37,
 'bisa': 38,
 'kalau': 39,
 'pemenang': 40,
 'utk': 41,
 'dr': 42,
 'jam': 43,
 'dengan': 44,
 'uinfo': 45,
 'nya': 46,
 'kamu': 47,
 'tri': 48,
 'ga': 49,
 'kuota': 50,
 'gratis': 51,
 'sd': 52,
 'ketik': 53,
 'ulang': 54,
 'care': 55,
 'bonus': 56,
 'hanya': 57,
 'sudah': 58,
 'pak': 59,
 'beli': 60,
 'berlaku': 61,
 'maaf': 62,
 'dgn': 63,
 'indosat': 64,
 'juga': 65,
 'bb': 66,
 'kita': 67,
 'itu': 68,
 'kalo': 69,
 'sama': 70,
 'nanti': 71,
 'kirim': 72,
 'mobil': 73,
 'telah': 74,
 'kasih': 75,
 'yth': 76,
 'sekarang': 77,
 'internetan': 

In [ ]:
sequences = tokenizer.texts_to_sequences(teks_corpus)
sequences

[[30,
  60,
  23,
  96,
  105,
  35,
  2,
  406,
  135,
  255,
  133,
  185,
  50,
  35,
  119,
  311,
  11,
  185,
  120,
  186,
  1,
  145,
  17,
  2,
  407,
  187],
 [35,
  29,
  57,
  18,
  162,
  218,
  106,
  3,
  26,
  113,
  188,
  77,
  65,
  2,
  30,
  52,
  1,
  145,
  188,
  77,
  187],
 [173, 76, 408, 50, 96, 3, 1, 153, 352, 1, 2, 1, 41, 17, 1, 23, 96, 33, 24],
 [173, 76, 408, 50, 96, 3, 1, 153, 352, 1, 2, 1, 41, 17, 1, 23, 96, 33, 24],
 [35, 29, 57, 18, 162, 218, 106, 3, 26, 113, 188, 77, 65, 2, 145, 1],
 [29,
  91,
  1,
  22,
  34,
  92,
  60,
  23,
  86,
  1,
  2,
  352,
  41,
  312,
  1,
  1,
  1,
  17,
  313,
  30,
  2,
  407],
 [7, 1, 63, 204, 18, 97, 1, 18, 97, 13, 1, 1, 1, 1, 283, 284, 1, 6],
 [473, 189, 219, 1, 1, 314, 78, 87, 1, 1, 1, 1, 105, 18, 34, 2, 1, 17, 2, 353],
 [188,
  1,
  1,
  1,
  1,
  283,
  6,
  7,
  1,
  1,
  13,
  1,
  174,
  1,
  188,
  1,
  46,
  2,
  125,
  47,
  53,
  1,
  1,
  72,
  4,
  6,
  474,
  1,
  18,
  42,
  1,
  1,
  1,
  188,
  1,
 

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = pad_sequences(sequences,padding='post',truncating='post')
sequences

array([[ 30,  60,  23, ...,   0,   0,   0],
       [ 35,  29,  57, ...,   0,   0,   0],
       [173,  76, 408, ...,   0,   0,   0],
       ...,
       [  1,  10,  72, ...,   0,   0,   0],
       [ 19,   1,   1, ...,   0,   0,   0],
       [ 15, 170, 334, ...,   0,   0,   0]], dtype=int32)

In [ ]:
import re

def text_transform_pipe(text,tokenizer):
  text = text.lower()
  text = re.sub(r'[^a-zA-Z ]', '', text)
  text = text.strip()
  text = [text]
  seq = tokenizer.texts_to_sequences(text)
  seq = pad_sequences(seq,padding='post',truncating='post',maxlen=59)
  result = tf.one_hot(indices=seq,depth=499)
  return result

In [ ]:
sequences.shape

(1143, 59)

In [ ]:
sequences[0]

array([ 30,  60,  23,  96, 105,  35,   2, 406, 135, 255, 133, 185,  50,
        35, 119, 311,  11, 185, 120, 186,   1, 145,  17,   2, 407, 187,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0], dtype=int32)

In [ ]:
sequences = tf.one_hot(indices=sequences,depth=sequences.max(),axis=-1)
sequences.shape

TensorShape([1143, 59, 499])

In [ ]:
sequences[0]

<tf.Tensor: shape=(59, 499), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [ ]:
teks_label_oh = tf.one_hot(indices=teks_label,depth=teks_label.max()+1)
teks_label_oh.shape

TensorShape([1143, 3])

In [ ]:
teks_label_oh

<tf.Tensor: shape=(1143, 3), dtype=float32, numpy=
array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)>

In [ ]:
X_train = sequences[:900]
X_test = sequences[900:]
y_train = teks_label_oh[:900]
y_test = teks_label_oh[900:]
print('X Train shape =',X_train.shape)
print('X Test shape =',X_test.shape)
print('y Train shape =',y_train.shape)
print('y test shape =',y_test.shape)

X Train shape = (900, 59, 499)
X Test shape = (243, 59, 499)
y Train shape = (900, 3)
y test shape = (243, 3)


In [ ]:
def rnn_model():
  input = tf.keras.layers.Input(shape=(59,499))
  x = tf.keras.layers.SimpleRNN(100,dropout=0.5)(input)
  output = tf.keras.layers.Dense(3,activation='softmax')(x)
  return tf.keras.Model(inputs=input,outputs=output)


In [ ]:
rnn_mod = rnn_model()

In [ ]:
rnn_mod.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 59, 499)]         0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 100)               60000     
                                                                 
 dense (Dense)               (None, 3)                 303       
                                                                 
Total params: 60,303
Trainable params: 60,303
Non-trainable params: 0
_________________________________________________________________


In [ ]:
rnn_mod.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0003),loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
rnn_mod.fit(X_train,y_train,validation_data=[X_test,y_test],epochs=50)

Epoch 1/50
29/29 [==============================] - 5s 109ms/step - loss: 1.0954 - accuracy: 0.3667 - val_loss: 0.8621 - val_accuracy: 0.8971
Epoch 2/50
29/29 [==============================] - 3s 96ms/step - loss: 0.9835 - accuracy: 0.5344 - val_loss: 0.5331 - val_accuracy: 0.8642
Epoch 3/50
29/29 [==============================] - 3s 99ms/step - loss: 0.8317 - accuracy: 0.6300 - val_loss: 0.6255 - val_accuracy: 0.7901
Epoch 4/50
29/29 [==============================] - 3s 104ms/step - loss: 0.6831 - accuracy: 0.7111 - val_loss: 0.3999 - val_accuracy: 0.8930
Epoch 5/50
29/29 [==============================] - 3s 101ms/step - loss: 0.6031 - accuracy: 0.7467 - val_loss: 0.5924 - val_accuracy: 0.8272
Epoch 6/50
29/29 [==============================] - 3s 90ms/step - loss: 0.5407 - accuracy: 0.7900 - val_loss: 0.5590 - val_accuracy: 0.8230
Epoch 7/50
29/29 [==============================] - 3s 109ms/step - loss: 0.4892 - accuracy: 0.8356 - val_loss: 0.7158 - val_accuracy: 0.7984
Epoch 8/5

In [ ]:
def prediksi(text,model,tokenizer):
  x = text_transform_pipe(text,tokenizer)
  hasil = model.predict(x)
  ind = hasil.argmax()
  if (ind == 0):
    print('"'+text+'"'+' << SMS normal dengan keyakinan '+str(hasil[0,ind]*100)+'%')
  elif (ind == 1):
    print('"'+text+'"'+' << SMS penipuan dengan keyakinan '+str(hasil[0,ind]*100)+'%')
  elif (ind == 2):
    print('"'+text+'"'+' << SMS Promo dengan keyakinan '+str(hasil[0,ind]*100)+'%')


In [ ]:
prediksi("Promo ini hanya anda bisa temukan di telkomsel",rnn_mod,tokenizer)
prediksi("SELAMAT ANDA BERUNTUNG MEMENANGKAN RP17.000.000",rnn_mod,tokenizer)
prediksi("dek kamu di rumah? mama minta pulsa dong, mama di kantor polisi soalnya",rnn_mod,tokenizer)
prediksi("Sayang kamu lagi ngapain sih, kok chatku gk dibales :(",rnn_mod,tokenizer)

"Promo ini hanya anda bisa temukan di telkomsel" << SMS Promo dengan keyakinan 78.09150815010071%
"SELAMAT ANDA BERUNTUNG MEMENANGKAN RP17.000.000" << SMS Promo dengan keyakinan 55.42901158332825%
"dek kamu di rumah? mama minta pulsa dong, mama di kantor polisi soalnya" << SMS penipuan dengan keyakinan 95.73825597763062%
"Sayang kamu lagi ngapain sih, kok chatku gk dibales :(" << SMS normal dengan keyakinan 99.06232953071594%
